apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome-service-deployment
  labels:
    app: welcome-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: welcome-service
  template:
    metadata:
      labels:
        app: welcome-service
    spec:
      containers:
        - name: welcome-service
          image: welcome-service:0.0.1
          ports:
            - containerPort: 8080